### ISSUE TITLE
Feature Request: Ability To Disable Simulation On Restore Object

### ISSUE THREAD

**Issue by Vegas-zzz** [code34/oo_pdw.Altis#2]
It would be extremely useful to be able to disable simulation when restoring certain objects.

Some objects have Physics enabled on them, which can cause issues when they are restored from the database. A perfect example of this would be tables and chairs. They like to jump around!

Recommend add a function named something like "loadObjectsNoSim" or similar.

**Comment by code34** [comment]
i'm looking about it

does an instant disable and after that enable simulation can fix this problem ?

**Comment by Vegas-zzz** [comment]
@code34 That might work.

One object I recommend testing with would be Sandbag Walls. Because of simulation enabled they always snap to the ground. This means players cannot stack them or have them floating in air.

**Comment by code34** [comment]
i just add the simulation support on the develop branch:
https://github.com/code34/oo_pdw.Altis/blob/develop/oo_pdw.sqf

can you check with this version ? 

The load & save object methods save the enablesimulation state of the object. If you want to turn off simulation just do it with your script with "enableSimulation" or througt the editor, save, and it should normaly retrieve the state you define previously.

I also fixed ATL/ASL position.

**Comment by Vegas-zzz** [comment]
Thanks, will test and let you know how it goes! Appreciate the support!

**Comment by Vegas-zzz** [comment]
I cannot seem to test because I keep getting an undefined variable error since updating to this branch of oo_pdw.sqf

I'm trying to run this script:

//Save Function

```
_pdw = ["new", "inidbi"] call OO_PDW;
["setDbName", "21st_Roadblocks"] call _pdw;

["setIncludingTypes", ["Land_CzechHedgehog_01_F"]] call _pdw;
"saveObjects" call _pdw;

   sleep 60;
```


Any ideas?

**Comment by code34** [comment]
can you send me the error message or logs or a .pbo file with error ?

**Comment by Vegas-zzz** [comment]
Figured it would be easier this way, since we run 10,000 mods hehe.

initServer.sqf

```
//INIDBI2 Database Startup For 21st Roadblocks

		call compilefinal preprocessFileLineNumbers "oo_pdw.sqf"; //This compiles the set code required to save/load data.

		 _pdw = ["new", "inidbi"] call OO_PDW; // This lets OO_PDW know a new database is required to be created
		["setDbName", "21st_Roadblocks"] call _pdw; // This sets the database's name.

		diag_log text "======Restore Roadblocks======";

		_objects = "loadObjects" call _pdw; //Loads all objects saved in the database
```

21st_SaveRoadblocks.sqf (will have to execute this via debug or another method)

```
_pdw = ["new", "inidbi"] call OO_PDW;
["setDbName", "21st_Roadblocks"] call _pdw;

["setIncludingTypes", ["Land_CzechHedgehog_01_F"]] call _pdw;
"saveObjects" call _pdw;

   sleep 60;
```

I get this error: https://i.imgur.com/Fy2ehRr.jpg

**Comment by code34** [comment]
It's a global error that means there is a syntax error with a ', or { something like that

but it s weird cause i don't have this error localy. 

are u sure you use the last version + oop.h ?
https://github.com/code34/oo_pdw.Altis/archive/develop.zip

can you try it with a simple sample example ?

**Comment by code34** [comment]
Hi Vegas, 

do you have anyfeedback about this ?

**Comment by Vegas-zzz** [comment]
I just tested this new function and it works! No issues. Thank you!
